// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: pb/svc/dir.proto

package svc

import (
	dir "/pb/unit/dir"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDirReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dir *dir.Dir `protobuf:"bytes,1,opt,name=Dir,proto3" json:"Dir,omitempty"`
}

func (x *CreateDirReq) Reset() {
	*x = CreateDirReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_dir_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDirReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirReq) ProtoMessage() {}

func (x *CreateDirReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_dir_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirReq.ProtoReflect.Descriptor instead.
func (*CreateDirReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_dir_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDirReq) GetDir() *dir.Dir {
	if x != nil {
		return x.Dir
	}
	return nil
}

type CreateDirRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateDirRes) Reset() {
	*x = CreateDirRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_dir_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDirRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirRes) ProtoMessage() {}

func (x *CreateDirRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_dir_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirRes.ProtoReflect.Descriptor instead.
func (*CreateDirRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_dir_proto_rawDescGZIP(), []int{1}
}

type DeleteDirReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDirReq) Reset() {
	*x = DeleteDirReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_dir_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDirReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDirReq) ProtoMessage() {}

func (x *DeleteDirReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_dir_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDirReq.ProtoReflect.Descriptor instead.
func (*DeleteDirReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_dir_proto_rawDescGZIP(), []int{2}
}

type DeleteDirRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDirRes) Reset() {
	*x = DeleteDirRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_dir_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDirRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDirRes) ProtoMessage() {}

func (x *DeleteDirRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_dir_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDirRes.ProtoReflect.Descriptor instead.
func (*DeleteDirRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_dir_proto_rawDescGZIP(), []int{3}
}

type GetDirReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDirReq) Reset() {
	*x = GetDirReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_dir_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDirReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirReq) ProtoMessage() {}

func (x *GetDirReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_dir_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirReq.ProtoReflect.Descriptor instead.
func (*GetDirReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_dir_proto_rawDescGZIP(), []int{4}
}

type GetDirRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dir *dir.Dir `protobuf:"bytes,1,opt,name=Dir,proto3" json:"Dir,omitempty"`
}

func (x *GetDirRes) Reset() {
	*x = GetDirRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_dir_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDirRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirRes) ProtoMessage() {}

func (x *GetDirRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_dir_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirRes.ProtoReflect.Descriptor instead.
func (*GetDirRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_dir_proto_rawDescGZIP(), []int{5}
}

func (x *GetDirRes) GetDir() *dir.Dir {
	if x != nil {
		return x.Dir
	}
	return nil
}

var File_pb_svc_dir_proto protoreflect.FileDescriptor

var file_pb_svc_dir_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x64, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x1a, 0x15, 0x70, 0x62, 0x2f, 0x75,
	0x6e, 0x69, 0x74, 0x2f, 0x64, 0x69, 0x72, 0x2f, 0x64, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x32, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x72, 0x52, 0x65,
	0x71, 0x12, 0x22, 0x0a, 0x03, 0x44, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x44, 0x69, 0x72,
	0x52, 0x03, 0x44, 0x69, 0x72, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44,
	0x69, 0x72, 0x52, 0x65, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44,
	0x69, 0x72, 0x52, 0x65, 0x71, 0x22, 0x0e, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44,
	0x69, 0x72, 0x52, 0x65, 0x73, 0x22, 0x0b, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x52,
	0x65, 0x71, 0x22, 0x2f, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x12,
	0x22, 0x0a, 0x03, 0x44, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x44, 0x69, 0x72, 0x52, 0x03,
	0x44, 0x69, 0x72, 0x32, 0xa8, 0x01, 0x0a, 0x03, 0x44, 0x69, 0x72, 0x12, 0x37, 0x0a, 0x09, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x72, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76,
	0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x14,
	0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69,
	0x72, 0x52, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f,
	0x73, 0x74, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76,
	0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x12, 0x2e,
	0x0a, 0x06, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x62,
	0x2e, 0x73, 0x76, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x42, 0x08,
	0x5a, 0x06, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_svc_dir_proto_rawDescOnce sync.Once
	file_pb_svc_dir_proto_rawDescData = file_pb_svc_dir_proto_rawDesc
)

func file_pb_svc_dir_proto_rawDescGZIP() []byte {
	file_pb_svc_dir_proto_rawDescOnce.Do(func() {
		file_pb_svc_dir_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_svc_dir_proto_rawDescData)
	})
	return file_pb_svc_dir_proto_rawDescData
}

var file_pb_svc_dir_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_svc_dir_proto_goTypes = []interface{}{
	(*CreateDirReq)(nil), // 0: pb.svc.CreateDirReq
	(*CreateDirRes)(nil), // 1: pb.svc.CreateDirRes
	(*DeleteDirReq)(nil), // 2: pb.svc.DeleteDirReq
	(*DeleteDirRes)(nil), // 3: pb.svc.DeleteDirRes
	(*GetDirReq)(nil),    // 4: pb.svc.GetDirReq
	(*GetDirRes)(nil),    // 5: pb.svc.GetDirRes
	(*dir.Dir)(nil),      // 6: pb.unit.dir.Dir
}
var file_pb_svc_dir_proto_depIdxs = []int32{
	6, // 0: pb.svc.CreateDirReq.Dir:type_name -> pb.unit.dir.Dir
	6, // 1: pb.svc.GetDirRes.Dir:type_name -> pb.unit.dir.Dir
	0, // 2: pb.svc.Dir.CreateDir:input_type -> pb.svc.CreateDirReq
	2, // 3: pb.svc.Dir.DeletePost:input_type -> pb.svc.DeleteDirReq
	4, // 4: pb.svc.Dir.GetDir:input_type -> pb.svc.GetDirReq
	1, // 5: pb.svc.Dir.CreateDir:output_type -> pb.svc.CreateDirRes
	3, // 6: pb.svc.Dir.DeletePost:output_type -> pb.svc.DeleteDirRes
	5, // 7: pb.svc.Dir.GetDir:output_type -> pb.svc.GetDirRes
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_svc_dir_proto_init() }
func file_pb_svc_dir_proto_init() {
	if File_pb_svc_dir_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_svc_dir_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDirReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_dir_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDirRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_dir_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDirReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_dir_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDirRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_dir_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDirReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_dir_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDirRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_svc_dir_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_svc_dir_proto_goTypes,
		DependencyIndexes: file_pb_svc_dir_proto_depIdxs,
		MessageInfos:      file_pb_svc_dir_proto_msgTypes,
	}.Build()
	File_pb_svc_dir_proto = out.File
	file_pb_svc_dir_proto_rawDesc = nil
	file_pb_svc_dir_proto_goTypes = nil
	file_pb_svc_dir_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DirClient is the client API for Dir service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DirClient interface {
	CreateDir(ctx context.Context, in *CreateDirReq, opts ...grpc.CallOption) (*CreateDirRes, error)
	DeletePost(ctx context.Context, in *DeleteDirReq, opts ...grpc.CallOption) (*DeleteDirRes, error)
	GetDir(ctx context.Context, in *GetDirReq, opts ...grpc.CallOption) (*GetDirRes, error)
}

type dirClient struct {
	cc grpc.ClientConnInterface
}

func NewDirClient(cc grpc.ClientConnInterface) DirClient {
	return &dirClient{cc}
}

func (c *dirClient) CreateDir(ctx context.Context, in *CreateDirReq, opts ...grpc.CallOption) (*CreateDirRes, error) {
	out := new(CreateDirRes)
	err := c.cc.Invoke(ctx, "/pb.svc.Dir/CreateDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dirClient) DeletePost(ctx context.Context, in *DeleteDirReq, opts ...grpc.CallOption) (*DeleteDirRes, error) {
	out := new(DeleteDirRes)
	err := c.cc.Invoke(ctx, "/pb.svc.Dir/DeletePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dirClient) GetDir(ctx context.Context, in *GetDirReq, opts ...grpc.CallOption) (*GetDirRes, error) {
	out := new(GetDirRes)
	err := c.cc.Invoke(ctx, "/pb.svc.Dir/GetDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirServer is the server API for Dir service.
type DirServer interface {
	CreateDir(context.Context, *CreateDirReq) (*CreateDirRes, error)
	DeletePost(context.Context, *DeleteDirReq) (*DeleteDirRes, error)
	GetDir(context.Context, *GetDirReq) (*GetDirRes, error)
}

// UnimplementedDirServer can be embedded to have forward compatible implementations.
type UnimplementedDirServer struct {
}

func (*UnimplementedDirServer) CreateDir(context.Context, *CreateDirReq) (*CreateDirRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDir not implemented")
}
func (*UnimplementedDirServer) DeletePost(context.Context, *DeleteDirReq) (*DeleteDirRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (*UnimplementedDirServer) GetDir(context.Context, *GetDirReq) (*GetDirRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDir not implemented")
}

func RegisterDirServer(s *grpc.Server, srv DirServer) {
	s.RegisterService(&_Dir_serviceDesc, srv)
}

func _Dir_CreateDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDirReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirServer).CreateDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.Dir/CreateDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirServer).CreateDir(ctx, req.(*CreateDirReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dir_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDirReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.Dir/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirServer).DeletePost(ctx, req.(*DeleteDirReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dir_GetDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDirReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirServer).GetDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.Dir/GetDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirServer).GetDir(ctx, req.(*GetDirReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dir_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.svc.Dir",
	HandlerType: (*DirServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDir",
			Handler:    _Dir_CreateDir_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _Dir_DeletePost_Handler,
		},
		{
			MethodName: "GetDir",
			Handler:    _Dir_GetDir_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/svc/dir.proto",
}
